// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_HLVv3bxzay6HWHPoZmyjeQDsumyaCU',
    appId: '1:902203386107:web:a3740f86b0fe83e1e8685e',
    messagingSenderId: '902203386107',
    projectId: 'notepad-pro-plus',
    authDomain: 'notepad-pro-plus.firebaseapp.com',
    storageBucket: 'notepad-pro-plus.appspot.com',
    measurementId: 'G-59JMELF61Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYUZlgHsrLkIOvTsgCr7SE2BRCOUnEq0A',
    appId: '1:902203386107:android:98842dfcb11a28b4e8685e',
    messagingSenderId: '902203386107',
    projectId: 'notepad-pro-plus',
    storageBucket: 'notepad-pro-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBOxdg9JGHtCJfSciZTuyOkn-trdzhZ-g',
    appId: '1:902203386107:ios:c01ffb93e35c0a15e8685e',
    messagingSenderId: '902203386107',
    projectId: 'notepad-pro-plus',
    storageBucket: 'notepad-pro-plus.appspot.com',
    iosBundleId: 'com.example.notepadProPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBOxdg9JGHtCJfSciZTuyOkn-trdzhZ-g',
    appId: '1:902203386107:ios:8ae3af80a4d1d32ce8685e',
    messagingSenderId: '902203386107',
    projectId: 'notepad-pro-plus',
    storageBucket: 'notepad-pro-plus.appspot.com',
    iosBundleId: 'com.example.notepadProPlus.RunnerTests',
  );
}
